package com.chinawiserv.dsp.dcm.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hotel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Hotel {
    /**
     * Database Column Remarks:
     *   城市id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.city
     *
     * @mbg.generated
     */
    private Integer city;

    /**
     * Database Column Remarks:
     *   酒店名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   酒店地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.zip
     *
     * @mbg.generated
     */
    private String zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.city
     *
     * @return the value of hotel.city
     *
     * @mbg.generated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.city
     *
     * @param city the value for hotel.city
     *
     * @mbg.generated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.name
     *
     * @return the value of hotel.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.name
     *
     * @param name the value for hotel.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.address
     *
     * @return the value of hotel.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.address
     *
     * @param address the value for hotel.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.zip
     *
     * @return the value of hotel.zip
     *
     * @mbg.generated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.zip
     *
     * @param zip the value for hotel.zip
     *
     * @mbg.generated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }
}