package com.chinawiserv.dsp.dcm.domain;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table city
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class User {
    /**
     * Database Column Remarks:
     *   城市id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   城市名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * Database Column Remarks:
     *   所属国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.country
     *
     * @mbg.generated
     */
    private String country;


}